---
title: "class92816"
author: "Kaari Loukusa"
date: "September 28, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Reading data
```{r}
mydiamonds=read.csv("diamonds.csv")



```


#Dimentions and names of variables
```{r}
dim(mydiamonds)
nrow(mydiamonds)
ncol(mydiamonds)

```

There are `r nrow(mydiamonds)` rows in our dataset.

```{r}
colnames(mydiamonds)
mydiamonds=mydiamonds[,2:11]

```

After knocking off the first col, I am now left with `r ncol(mydiamonds)`


#Save my truncated file
```{r}
save(mydiamonds,file="mydiamonds.Rda")
```


#data structure
```{r}
str(mydiamonds)
```


#summary
```{r}
summary(mydiamonds[,c("carat","cut")])
summary(mydiamonds[,c(1,3)])
```


#number of levels of a factor variable
```{r}
nlevels(mydiamonds$clarity)
levels(mydiamonds$clarity)
```


```{r}
fairdiamonds=mydiamonds[mydiamonds$cut=="Fair",]
```


```{r}
levels(fairdiamonds$cut)
summary(fairdiamonds$cut)
```


#refactoring after a subset using a factor variable
```{r}
fairdiamonds$cut=factor(fairdiamonds$cut)
summary(fairdiamonds$cut)
```



